#Port 80 will never be hit while the master-edge-router is being used since it automatically forwards all traffic to port 8081 which goes directly to 443
<VirtualHost *:80>
  ServerName matomo.${BASE_DOMAIN}

  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteCond %{REQUEST_URI} !^\/\.well-known\/.*$
  RewriteRule (.*) https://matomo.${BASE_DOMAIN}/$1 [R,L]

</VirtualHost>

<VirtualHost *:443>

  ServerName matomo.${BASE_DOMAIN}

  SSLProtocol All -SSLv2 -SSLv3
  SSLCompression Off
  SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+AESGCM EECDH EDH+AESGCM EDH+aRSA HIGH !MEDIUM !LOW !aNULL !eNULL !L$
  SSLEngine On
  SSLProxyEngine On

  SSLCertificateFile /etc/certs/${BASE_DOMAIN}/cert.crt
  SSLCertificateKeyFile /etc/certs/${BASE_DOMAIN}/cert.key

  #SSLCertificateFile /certs/letsencrypt/live/${BASE_DOMAIN}/fullchain.pem
  #SSLCertificateKeyFile /certs/letsencrypt/live/${BASE_DOMAIN}/privkey.pem

  Header set Access-Control-Allow-Origin "*"

  RequestHeader set X-Forwarded-Proto "https"

  ProxyPreserveHost On
  ProxyPass / http://matomo/
  ProxyPassReverse / http://matomo.${BASE_DOMAIN}/

  # Use RewriteEngine to handle websocket connection upgrades
  RewriteEngine On
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule /(.*) ws://matomo/$1 [P,L]

  ServerAdmin support@humlab.umu.se

  ErrorLog ${APACHE_LOG_DIR}/matomo-error.log
  CustomLog ${APACHE_LOG_DIR}/matomo-access.log combined

  # ErrorLog  '|usr/bin/rotatelogs -l -f ${APACHE_LOG_DIR}/matomo-error.%Y.%m.%d.log 900'
  # CustomLog '|usr/bin/rotatelogs -l -f ${APACHE_LOG_DIR}/matomo-access.%Y.%m.%d.log 900' combined

</VirtualHost>
