#!/bin/bash
#
# Download Google Fonts for Air-gapped Builds
# ============================================
# Downloads the fonts used by the VISP webclient so builds can work offline.
# These fonts are .gitignored to avoid redistributing copyrighted files.
#
# Usage:
#   ./scripts/download-fonts.sh
#
# After running, rebuild the Apache image to include fonts:
#   podman build -t visp-apache -f docker/apache/Dockerfile .
#
# See docs/AIRGAP.md for more details.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
FONTS_DIR="$PROJECT_ROOT/external/webclient/fonts"

echo "=== VISP Font Downloader ==="
echo ""
echo "Downloading fonts used by webclient for air-gapped builds..."
echo "Target: $FONTS_DIR"
echo ""

# Create fonts directory
mkdir -p "$FONTS_DIR"

# Font URLs from Google Fonts
# Note: These URLs may change. Get fresh ones from fonts.google.com if needed.
# The webclient uses:
#   - Saira Semi Condensed (weight 300)
#   - Source Sans Pro (regular)

echo "Downloading Saira Semi Condensed (weight 300)..."
curl -fsSL -o "$FONTS_DIR/saira-semi-condensed-300.woff2" \
    "https://fonts.gstatic.com/s/sairasemicondensed/v13/U9MD6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXdvWCNu.woff2" || {
    echo "Warning: Failed to download Saira Semi Condensed. Font URL may have changed."
    echo "Visit https://fonts.google.com/specimen/Saira+Semi+Condensed to get fresh URL."
}

echo "Downloading Source Sans Pro (regular)..."
curl -fsSL -o "$FONTS_DIR/source-sans-pro-regular.woff2" \
    "https://fonts.gstatic.com/s/sourcesanspro/v22/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2" || {
    echo "Warning: Failed to download Source Sans Pro. Font URL may have changed."
    echo "Visit https://fonts.google.com/specimen/Source+Sans+Pro to get fresh URL."
}

# Create fonts.css with @font-face rules
echo "Creating fonts.css..."
cat > "$FONTS_DIR/../fonts.css" << 'EOF'
/* Local fonts for air-gapped VISP builds */
/* Generated by scripts/download-fonts.sh */

@font-face {
  font-family: 'Saira Semi Condensed';
  font-style: normal;
  font-weight: 300;
  font-display: swap;
  src: url('assets/fonts/saira-semi-condensed-300.woff2') format('woff2');
}

@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('assets/fonts/source-sans-pro-regular.woff2') format('woff2');
}
EOF

echo ""
echo "✓ Fonts downloaded to: $FONTS_DIR"
echo "✓ fonts.css created at: $FONTS_DIR/../fonts.css"
echo ""
echo "Files created:"
ls -la "$FONTS_DIR"
echo ""
ls -la "$FONTS_DIR/../fonts.css"
echo ""
echo "Next steps:"
echo "  1. Rebuild Apache image: podman build -t visp-apache -f docker/apache/Dockerfile ."
echo "  2. The Dockerfile will automatically include these fonts in air-gapped builds."
echo ""
echo "Note: These font files are .gitignored. Run this script on each machine that needs"
echo "      to build air-gapped images."
