library(emuR)
dbPath = file.path(Sys.getenv("PROJECT_PATH"), "Data", "humlabspeech_emuDB")
VISPDB = load_emuDB(dbPath)
sessions <- list_sessions(VISPDB)
sessionsJson <- jsonlite::toJSON(sessions)
print(sessionsJson)
